codecov:
  notify:
    after_n_builds: 2
    wait_for_ci: yes

flag_management:
  individual_flags:
    - name: typescript
      statuses:
        - type: project
          target: 30%
    - name: python
      statuses:
        - type: project
          target: 30%
