name: Base image CD

on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  buildImages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "image_name=onscene/flojoy" >> $GITHUB_ENV
      - run: echo "commit_id_short=$(git rev-parse --short $GITHUB_SHA)" >> $GITHUB_ENV
      - name: Build Base Image
        run: BASE_IMAGE_TAG=$commit_id_short docker-compose -f docker-compose-base.yml build base-image
      - name: Tag latest
        run: BASE_IMAGE_TAG=latest docker-compose -f docker-compose-base.yml build base-image
      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.RW_DOCKER_HUB_USER_NAME }}
          password: ${{ secrets.RW_DOCKER_HUB_ACCESS_TOKEN }}
      - name: Push image
        run: docker image push $image_name:$commit_id_short && docker image push $image_name:latest
